server:
    port: 8000
spring:
    # security 使能
    output.ansi.enabled: ALWAYS
    application:
        name: eureka-demo
    security.basic.enabled: false
    datasource:
        url: jdbc:mysql://118.24.19.64:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    kafka:
        producer:
            retries: 0
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            bootstrap-servers: 118.24.19.64:9092
        consumer:
            group-id: hanzhipan
            auto-offset-reset: earliest
            enable-auto-commit: true
            auto-commit-interval: 100
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            bootstrap-servers: 118.24.19.64:9092
eureka:
    instance:
        hostname: 118.24.19.64
        port: 8761
        prefer-ip-address: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    client:
        serviceUrl:
            defaultZone: http://user:123456@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
        evictionIntervalTimerInMs: 5000
feign:
    hystrix:
        enabled: true
mybatis:
    mapperLocations: classpath*:/mapper/**Mapper.xml
    typeAliasesPackage: com.springbootdemo.mapper