spring:
    datasource:
        name: test
        url: jdbc:mysql://congcongxiao.mysql.rds.aliyuncs.com:3306/test?characterEncoding=utf8&useSSL=true
        username: root
        password: HUANGhongdan0823
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    typeAliasesPackage: com.springbootdemo.entity
    mapperLocations: classpath:mapper/*.xml