server:
    port: 8000
spring:
    datasource:
        name: test
        url: jdbc:mysql://congcongxiao.mysql.rds.aliyuncs.com:3306/test?characterEncoding=utf8&useSSL=true
        username: root
        password: HUANGhongdan0823
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    kafka:
      producer:
        retries: 0
        batch-size: 16384
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        broker-list: 118.24.19.64:9092
      consumer:
        zookeeper: 118.24.19.64:2181
        group-id: hanzhipan
        auto-offset-reset: earliest
        enable-auto-commit: true
        auto-commit-interval: 100
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
    mapperLocations: classpath*:/mapper/**Mapper.xml
    typeAliasesPackage: com.springbootdemo.mapper